// <auto-generated />
using System;
using GrapQLSample.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GrapQLSample.Api.Migrations
{
    [DbContext(typeof(GraphQLSampleDBContext))]
    [Migration("20190617130534_First commit")]
    partial class Firstcommit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("GrapQLSample.Data.Entities.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<string>("Line1");

                    b.Property<string>("Line2");

                    b.Property<int>("PostalCode");

                    b.HasKey("Id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("GrapQLSample.Data.Entities.Attendee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Company");

                    b.Property<long?>("CurrentAddressId");

                    b.Property<string>("Email");

                    b.Property<long?>("HomeTownAddressId");

                    b.Property<string>("LastName");

                    b.Property<string>("Name");

                    b.Property<string>("Position");

                    b.HasKey("Id");

                    b.HasIndex("CurrentAddressId");

                    b.HasIndex("HomeTownAddressId");

                    b.ToTable("Attendees");
                });

            modelBuilder.Entity("GrapQLSample.Data.Entities.Movie", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Director");

                    b.Property<string>("Genre");

                    b.Property<string>("Title");

                    b.Property<short>("Year");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("GrapQLSample.Data.Entities.Attendee", b =>
                {
                    b.HasOne("GrapQLSample.Data.Entities.Address", "CurrentAddress")
                        .WithMany()
                        .HasForeignKey("CurrentAddressId");

                    b.HasOne("GrapQLSample.Data.Entities.Address", "HomeTownAddress")
                        .WithMany()
                        .HasForeignKey("HomeTownAddressId");
                });
#pragma warning restore 612, 618
        }
    }
}
